"""Typed protocols for narrow auditable tools."""

from typing import Any, Protocol

from ..models import ChangeCommand, CommandExecutionResult, EvidenceReference, RecordSnapshot, Relationship


class RecordTools(Protocol):
    async def get_record_snapshot(self, tenant_id: str, record_id: str) -> RecordSnapshot: ...

    async def get_related_parties(self, tenant_id: str, record_id: str) -> list[Relationship]: ...

    async def get_account_restrictions(self, tenant_id: str, record_id: str) -> list[str]: ...

    async def check_record_version(self, tenant_id: str, record_id: str, expected_version: int) -> bool: ...


class IdentityTools(Protocol):
    async def get_customer_master(self, tenant_id: str, customer_id: str) -> dict[str, Any]: ...

    async def match_person_name(self, requested_name: str, authoritative_name: str) -> dict[str, Any]: ...


class OrganizationTools(Protocol):
    async def lookup_charity_registration(self, registration_number: str, country: str) -> dict[str, Any]: ...

    async def get_authorized_signatories(self, tenant_id: str, record_id: str) -> list[dict[str, Any]]: ...


class EvidenceTools(Protocol):
    async def get_document(self, document_id: str) -> EvidenceReference: ...

    async def extract_document_fields(self, document_id: str, fields: list[str]) -> dict[str, Any]: ...

    async def compare_document_fact(self, document_id: str, field: str, expected_value: Any) -> dict[str, Any]: ...


class ComplianceTools(Protocol):
    async def check_legal_hold(self, tenant_id: str, record_id: str) -> dict[str, Any]: ...

    async def screen_sanctions(self, tenant_id: str, subject_id: str) -> dict[str, Any]: ...


class ExecutionTools(Protocol):
    async def prepare_record_change(self, command: ChangeCommand) -> ChangeCommand: ...

    async def execute_approved_change(self, command: ChangeCommand) -> CommandExecutionResult: ...


class ToolGatewayProtocol(Protocol):
    async def invoke(self, tool_name: str, payload: dict[str, Any]) -> Any: ...

